name: Build and Push to Docker Hub

on:
  push:
    branches: [ "main" ]   # Change if needed
  workflow_dispatch:        # Allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build and push image
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: japitpit/dockertesting:latest, japitpit/dockertesting:${{ github.sha }}

